### PR TITLE
Dropbear:update to 2020.81

### PR DESCRIPTION
**Pull request by Yh793**

### CODE REVIEW

**Comment by omnjpa27516** [comment]
@Yh793 @hanwckf 请问一下编译报错如何处理呢？zlib已经安装了
`checking for deflate in -lz... no
configure: error: *** zlib missing - install first or check config.log ***
make[3]: *** [Makefile:25: configure] Error 1
make[3]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
make[2]: *** [Makefile:18: config_test] Error 2
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
make[1]: *** [Makefile:221: all] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
make: *** [Makefile:202: user_only] Error 2
Error: Process completed with exit code 2.`

**Comment by ChenyangS** [comment]
> @Yh793 @hanwckf 请问一下编译报错如何处理呢？zlib已经安装了
> 
> > checking for crypt... no
> > checking for crypt in -lcrypt... no
> > checking for deflate in -lz... no
> > configure: error: *** zlib missing - install first or check config.log ***
> > make[3]: *** [Makefile:25: configure] Error 1
> > make[3]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
> > make[2]: *** [Makefile:18: config_test] Error 2
> > make[2]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
> > make[1]: *** [Makefile:221: all] Error 2
> > make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
> > make: *** [Makefile:202: user_only] Error 2
> > Error: Process completed with exit code 2
复现了，小白猜代码迁移还是有问题

**Comment by omnjpa27516** [comment]
@hanwckf 烦请修复一下编译问题吧

**Comment by PigodChen** [comment]
> > @Yh793 @hanwckf 请问一下编译报错如何处理呢？zlib已经安装了
> > > checking for crypt... no
> > > checking for crypt in -lcrypt... no
> > > checking for deflate in -lz... no
> > > configure: error: *** zlib missing - install first or check config.log ***
> > > make[3]: *** [Makefile:25: configure] Error 1
> > > make[3]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
> > > make[2]: *** [Makefile:18: config_test] Error 2
> > > make[2]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
> > > make[1]: *** [Makefile:221: all] Error 2
> > > make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
> > > make: *** [Makefile:202: user_only] Error 2
> > > Error: Process completed with exit code 2
> > > 复现了，小白猜代码迁移还是有问题

@ChenyangS @omnjpa27516    dropbear -> makefile -> ./configure 里边加配置 --disable-harden \

**Comment by 90999** [comment]
make[2]: Entering directory '/opt/rt-n56u/trunk/user/dropbear'
( if [ -f ./config_done ]; then \
	echo "the same configuration"; \
else \
	make configure && touch config_done; \
fi )
make[3]: Entering directory '/opt/rt-n56u/trunk/user/dropbear'
( cd dropbear-202X.XX ; \
autoreconf -v; \
./configure \
	--prefix=/usr \
	--disable-lastlog \
	--disable-utmp \
	--disable-utmpx \
	--disable-wtmp \
	--disable-wtmpx \
	--disable-loginfunc \
	--disable-pututline \
	--disable-pututxline \
	--enable-zlib \
	--enable-bundled-libtom \
	--host=mipsel-linux \ 
/bin/sh: 15: Syntax error: end of file unexpected (expecting ")")
Makefile:25: recipe for target 'configure' failed
make[3]: *** [configure] Error 2
make[3]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
Makefile:18: recipe for target 'config_test' failed
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear'
make[2]: *** [config_test] Error 2
make[1]: *** [all] Error 2
Makefile:222: recipe for target 'all' failed
make: *** [user_only] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
Makefile:202: recipe for target 'user_only' failed
Error: Process completed with exit code 2.


https://github.com/90999/rt-n56u/blob/master/trunk/user/dropbear/Makefile
https://github.com/90999/rt-n56u/blob/master/trunk/configs/templates/PSG1218_nano.config

开了DROPBEAR就不行

**Comment by lhuanyun** [comment]
> make[2]: Entering directory '/opt/rt-n56u/trunk/user/dropbear' ( if [ -f ./config_done ]; then echo "the same configuration"; else make configure && touch config_done; fi ) make[3]: Entering directory '/opt/rt-n56u/trunk/user/dropbear' ( cd dropbear-202X.XX ; autoreconf -v; ./configure --prefix=/usr --disable-lastlog --disable-utmp --disable-utmpx --disable-wtmp --disable-wtmpx --disable-loginfunc --disable-pututline --disable-pututxline --enable-zlib --enable-bundled-libtom --host=mipsel-linux \ /bin/sh: 15: Syntax error: end of file unexpected (expecting ")") Makefile:25: recipe for target 'configure' failed make[3]: *** [configure] Error 2 make[3]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear' Makefile:18: recipe for target 'config_test' failed make[2]: Leaving directory '/opt/rt-n56u/trunk/user/dropbear' make[2]: *** [config_test] Error 2 make[1]: *** [all] Error 2 Makefile:222: recipe for target 'all' failed make: *** [user_only] Error 2 make[1]: Leaving directory '/opt/rt-n56u/trunk/user' Makefile:202: recipe for target 'user_only' failed Error: Process completed with exit code 2.
> 
> https://github.com/90999/rt-n56u/blob/master/trunk/user/dropbear/Makefile https://github.com/90999/rt-n56u/blob/master/trunk/configs/templates/PSG1218_nano.config
> 
> 开了DROPBEAR就不行

你把格式都该没了

**Pull request merged**
