### PR TITLE
Xiaomi R2100 FIXED Power/Internet LEDs

### PR DESCRIPTION
**Pull request by emirefek**
I was defined them wrong at my previous PR. This should fix them.

### CODE REVIEW

**Comment by butinhi** [comment]
Fix but 1 light is blue and 1 light is light blue, not the same.

**Comment by emirefek** [comment]
> Fix but 1 light is blue and 1 light is light blue, not the same.

Yes. You cannot light up "light blue" with single gpio port, you need to combine 2 ports for it. And I configured it for dual blue led. And it's true. Can be merged safely.

**Comment by butinhi** [comment]
> > Fix but 1 light is blue and 1 light is light blue, not the same.
> 
> Yes. You cannot light up "light blue" with single gpio port, you need to combine 2 ports for it. And I configured it for dual blue led. And it's true. Can be merged safely.
Yes. But not like original firmware.

**Comment by emirefek** [comment]
How is it im original firmware?

**Comment by butinhi** [comment]
> How is it in original firmware?

Both 2 lights are same blue.

**Comment by emirefek** [comment]
It should be like that.

**Comment by butinhi** [comment]
> It should be like that.

Better if same color.

**Comment by emirefek** [comment]
> > It should be like that.
> 
> Better if same color.

It is damn same color? Wtf.

**Comment by butinhi** [comment]
> > > It should be like that.
> > 
> > 
> > Better if same color.
> 
> It is damn same color? Wtf. Are you joke.?

No joke. Power light is quite light blue than Wan light.

**Pull request merged**
